### ISSUE TITLE
En la introducción, hablar de los ejemplos de viodejuegos procedurales de actualidad para que el/la revisor/a entienda el calado de los posibles resultados

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#21]
Proposed: En la introducción, hablar de los ejemplos de viodejuegos procedurales de actualidad para que el/la revisor/a entienda el calado de los posibles resultados

**Comment by JJ** [comment]
No levantes demasiadas expectativas sobre el resultado. Recuerda que, a este nivel, no estás _realmente_ generando historias de personajes, sólo "tramas" o "esqueletos".

**Comment by rhgarcia** [comment]
Ok, he hablado también de ello en el primer párrafo de la introducción. He usado el ejemplo de No Man's sky, el máximo ejemplo de PCG, que ganó 3 premios en el pasado E3 de 2014.
@amorag te lo asigno para que le eches un ojo también.

**Comment by JJ** [comment]
@amorag igual que antes si no puedes hacerlo reasigna. Por mi parte, visto lo que hay y salvo notas añadidas, por mi está bien @raiben

**Comment by rhgarcia** [comment]
OK, vistas las notas. Muchas gracias @JJ. Voy cerrando los issues.

**Comment by amorag** [comment]
Acabo de ver esto, sorry. Lo tenía en mente, pero no sabía su caducidad. XD

Weno, comento cosas:

El párrafo inicial yo lo veo un poco innecesario con ese detalle.

Si el artículo va para la revista IEEE ToCIAIG, ahí ya saben lo importantes que son los videojuegos. :D
Además, dicha revista tiene un límite de 12 páginas si no me equivoco, por lo que, lo que se pueda ahorrar y usar en otras cosas más necesarias, mejor. ;)

Yo lo dejaría así:

Videogames have evolved in the last years into a mass medium and a very important industry \cite{esa_century_2014}. In this competitive context, the
Procedural Content Generation (PCG) is boosting its
popularity, mainly due to two reasons: the cost reduction that the automatic generation implies to the developers, and the re-playability that it offers to the players. As a recent example,
\textit{No man's sky}, an indie adventure videogame where planets,
fauna and flora are created procedurally, won three Game Critics
Awards, including Best Original Game and the Special Commendation for
Innovation, in the past Electronic Entertainment Expo 2014, a
reference annual trade show for the video game
industry\footnote{\url{http://www.gamecriticsawards.com/winners.html}}. 

Si falta espacio incluso se podría reducir más. ;)

**Comment by rhgarcia** [comment]
Gracias! Como no me lo habías reasignado no lo había visto. He cambiado el párrafo como indicas :-)

**Comment by amorag** [comment]
Ok, entonces después de revisarlo te lo reasigno. Oído cocina. :D
